language: cpp

compiler:
    - clang
    #- gcc
    # travis use gcc 4.6 which currently doesn't support override keyword

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-test-dev

script:
    - mkdir build/ && cd build/
    - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=1
    - make && make test
